### ISSUE TITLE
Error on playback in media browser

### ISSUE THREAD

**Issue by yolani** [JimStar/reolink_cctv#107]
**Describe the bug**
If I click on a thumbnail from the integration in the media browser I always get an "unknown error while searching the media". Additionally there is an exception logged in HA event log.

**To Reproduce**
Nable integration, configure camera, go to media browser, click thumbnail of a recording from reeling camera

**Expected behavior**
Stream is played?

**Debug log would be very helpful**

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/decorators.py", line 27, in _handle_async_response
    await func(hass, connection, msg)
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 192, in websocket_resolve_media
    media = await async_resolve_media(hass, msg["media_content_id"])
  File "/usr/src/homeassistant/homeassistant/components/media_source/__init__.py", line 155, in async_resolve_media
    return await item.async_resolve()
  File "/usr/src/homeassistant/homeassistant/components/media_source/models.py", line 83, in async_resolve
    return await self.async_media_source().async_resolve_media(self)
  File "/config/custom_components/reolink_cctv/media_source.py", line 126, in async_resolve_media
    stream = create_stream(self.hass, url, {})
TypeError: create_stream() missing 1 required positional argument: 'dynamic_stream_

**Screenshots**
<img width="449" alt="image" src="https://user-images.githubusercontent.com/219931/206496032-8368d358-b76f-4ab7-821e-ce91d670900e.png">

**Environment:**
Please provide useful information about your environment, like:
- Home Assistant version: 2022.12.0
- Reolink NVR/camera model: RLC-810A
- NVR/camera firmware v3.1.0.764_22022803

**Additional context**
Tried with Chrome and Safari, both do not work.

**Comment by Crush-Steelpunch** [comment]
I'm seeing the same, I'm using reolink_cctv-0.0.39 HomeAssistant 2022.12

**Comment by yolani** [comment]
It still does not work for me with the latest release, although I now get a different error
![image](https://user-images.githubusercontent.com/219931/206849328-d4511394-d994-411d-b369-fa741a9e55a8.jpeg)

**Comment by JimStar** [comment]
Please attach a full debug log.

**Comment by yolani** [comment]
There is not much with default logging settings

[140124332099520] Error handling message: Stream integration is not set up. (unknown_error) from 172.21.0.1 (Mozilla/5.0 (iPhone; CPU iPhone OS 16_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Home Assistant/2022.10.1 (io.robbie.HomeAssistant; build:2022.424; iOS 16.1.2) Mobile/HomeAssistant, like Safari)

You want debug logs from your intwegration?

**Comment by JimStar** [comment]
Just look at the issue template.

**Comment by JimStar** [comment]
> `Stream integration is not set up`

Looks like not this component's problem.

[https://github.com/home-assistant/core/issues/42389](https://github.com/home-assistant/core/issues/42389)

And looks like the new HA **2022.12** has a lot of problems, in addition to completely broken backward compatibility for some components (I've fixed **some** of them in this version, but looks like not all of them).  
It's even harder in the situation where I'm still not able to update to 2022.12 myself, 'cause I use HA as a TrueNAS plugin where it is of a 2022.8 version. So, no way to test this for me before it gets updated by the developer.

**Comment by yolani** [comment]
I got the stream working with the hints in the HA core issue, unfortunately I still get a lot of exceptions.

I'll just be patient for now until you manage to upgrade ;-)
