### ISSUE TITLE
command "SetEmail" error

### ISSUE THREAD

**Issue by garry0garry** [JimStar/reolink_cctv#30]
Home Assistant 2022.10.4, Frontend 20221010.0, HACS 1.28.2, Reolink IP NVR/cameras 0.0.15

Reolink RLC-520A hw IPC_523128M5MP v3.1.0.951_22041566 - 9 pcs.
Reolink RLC-520A hw IPC_523128M5MP_V2 v3.1.0.1228_22082201 - 2 pcs.
Reolink RLC-511WA hw IPC_523128M5MP v3.1.0.956_22041509 - 1 pc.

Settings:
HTTP, rtsp
Motion sensor off delay (seconds) - 60
Connection timeout (seconds) - 120

```
logger:
  default: warning
  logs:
    homeassistant.core: warning
    custom_components.reolink_cctv: debug
    reolink_ip: debug
```

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/switch.py:182
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 12:05:55 (12 occurrences)
Last logged: 12:07:33

Host 192.168.50.63:80: command "SetEmail" error.
Host 192.168.50.162:80: command "SetEmail" error.
Host 192.168.50.72:80: command "SetEmail" error.
Host 192.168.50.37:80: command "SetEmail" error.
Host 192.168.50.14:80: command "SetEmail" error.

```
Debug-log in attachment.
[home-assistant.copy.zip](https://github.com/JimStar/reolink_cctv/files/9808810/home-assistant.copy.zip)

**Comment by JimStar** [comment]
This is some other issue... Could you please attach a log of this error?..

**Comment by JimStar** [comment]
I think I know what's happening. Will post a new release soon...

**Comment by garry0garry** [comment]
Fixed. Thank you!

**Comment by JimStar** [comment]
If you are able to find and edit text files on your HA system - then I could suggest you one thing you could test, trying to workaround your cameras' login issues...

**Comment by garry0garry** [comment]
I have no problem editing source code in XA. I have a problem with free time. I can't always answer quickly, but I'll try.

I haven't had any problems logging in since yesterday. I will continue to monitor the situation.

**Comment by JimStar** [comment]
Yea, the component just logins eventually anyway.  
But I've still seen these login errors you posted after recent versions, so this means it still gets them from your cameras from time to time. In this case it needs to try to re-login again (it re-tries it every one minute), and eventually it happens OK again after one or more tries/minutes... until next time. Every "next time" happens every 55 minutes, because the login-session is only valid for one hour, after that the component must re-login into each camera anyway.

While it is not logged in for some time due to this error - it will still continue to receive motion-notifications it had already subscribed to. And in your happy case your cameras send **rich** kind of notifications, where the component has all the needed info inside these notifications, which means the component doesn't need to use the login session to send/receive additional data to/from cameras.  
But it would not be able **to re-subscribe** (to continue be notified) until it gets logged in again (and the subscription lasts only 15 minutes). Thus, if there would be a "happy" coincidence of a failed log-in (and it could fail for a few times in row, which means for a few minutes then), and the previous subscription expires exactly in the beginning of this period - then it will not be able to re-subscribe, and some motion events could be lost (no notifications would be sent by cameras)...

So you better continue poking Reolink support with a stick, so that they fix this...  
And you can try some edits/tests if future if you'd get any time for that... not sure that it would help though, just some thoughts... The proper thing of course would be to have this fixed by Reolink...

**Comment by JimStar** [comment]
...Actually, after some thought - the re-subscription may still work OK, even if the login session failed. It uses digest for authentication. But any camera state changes will not be reflected in the component, until after it re-logins again... So, should be not a very big deal in your case...

**Comment by garry0garry** [comment]
> If you are able to find and edit text files on your HA system - then I could suggest you one thing you could test, trying to workaround your cameras' login issues...

After the reboot, I see a temporary connection error:

```
2022-10-20 20:31:27.242 ERROR (MainThread) [reolink_ip.api] Host 192.168.50.27:80: login attempt failed.
2022-10-20 20:31:27.246 WARNING (MainThread) [homeassistant.config_entries] Config entry 'cam11' for reolink_cctv integration not ready yet: Error while trying to setup 192.168.50.27:80: failed to connect to device: "" .; Retrying in the background
```
[home-assistant.zip](https://github.com/JimStar/reolink_cctv/files/9832727/home-assistant.zip)

In my case it is not so important. Nonetheless. What can I test?

**Comment by JimStar** [comment]
I don't remember exactly the Python packages path to the file on HA system (I'm not at home right now), but should be somewhere in `/usr/.../homeassistant/.../site-packages/reolink-ip`.  
You need to open the `api.py` file from that path. Go to line **557**, it should be like this:
`# asyncio.sleep(0.5)`  
remove the hash and space after the hash, and replace the `0.5` by `5.0`. This would make a BIG enough delay after logging in. If the reason is that the camera-firmware is sluggish and/or does something in different threads that are not synchronized correctly (the session is confirmed to requester **before** it gets fully functional and available) - then this delay could help.

I did not want to test it with such a big delay in a normal release for **every other** users who has no such problems with their devices (I'm one of them). But if this helps for you - then I'll implement additional "delay" setting in the integration config as a workaround to this bug, and just make it "0" by default...

**Comment by JimStar** [comment]
...And delete the `__pycache__` folder in the `reolink-ip` directory after you made the changes. And restart HA **after** that...

**Comment by garry0garry** [comment]
```
$ uname -a
Linux MyHomeAssistant 5.15.0-50-generic #56-Ubuntu SMP Tue Sep 20 13:23:26 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

$ sudo docker exec -ti homeassistant exec bash

bash-5.1# find /usr/ -name reolink*
/usr/local/lib/python3.10/site-packages/reolink_ip
/usr/local/lib/python3.10/site-packages/reolink
/usr/local/lib/python3.10/site-packages/reolink_ip-0.0.22.dist-info
/usr/local/lib/python3.10/site-packages/reolink-0.0.62.dist-info
bash-5.1# cd /usr/local/lib/python3.10/site-packages/reolink_ip
bash-5.1# cat api.py | grep asyncio.sleep
                        # asyncio.sleep(0.5)
bash-5.1# vi api.py 
bash-5.1# cat api.py | grep asyncio.sleep
                        asyncio.sleep(5)
bash-5.1# rm -rf __pycache__
bash-5.1# exit
$ sudo docker stop homeassistant
$ sudo docker start homeassistant
```

```
Logger: reolink_ip.api
Source: custom_components/reolink_cctv/host.py:173
Integration: Reolink IP NVR/camera (documentation, issues)
First occurred: 22:56:39 (1 occurrences)
Last logged: 22:56:39

Host 192.168.50.27:80: login attempt failed.
```

```
Logger: homeassistant.config_entries
Source: config_entries.py:395
First occurred: 22:56:39 (1 occurrences)
Last logged: 22:56:39

Config entry 'cam11' for reolink_cctv integration not ready yet: Error while trying to setup 192.168.50.27:80: failed to connect to device: "".; Retrying in background
```

I see "reolink_ip", "reolink-ip" does not...

**Comment by JimStar** [comment]
Yes, `reolink_ip` is correct, I made a typo.  
OK, it makes it clear that the bug in the firmware is not just some simple lag... They just completely ignore the successful login they accepted just a second before, and reject the very next command sent to a camera with a correct session-token in it... And a minute later suddenly accept **absolutely the same** sequence that was rejected previously.  
Definitely a Reolink bug. And looks like no workarounds possible on this component's side unfortunately. They need to fix this - this is the only way.

I like how the guy just looked into the log, and told you the problem is "*single quotes*" in the JSON command, without even looking that **this same** "*wrong-format*" in his words command is still **accepted** by **the same** camera just a minute later, and accepted all over the rest of the log...  
So in their skewed logic - **the same camera** somehow thinks *this time the JSON command is wrong*, but the very next time when **the same format command** is sent to it - ***this** time this **same** command is suddenly **correct***.  
No, this doesn't work like this. If the JSON would be wrong from the point of view of their firmware - it would **not** be accepted in **any** attempt to send it to a camera. But if the camera accepted it many times, and just **in some random cases** fails to accept it - then it is definitely nothing to do with a "*wrong*" JSON format.
I hate to argue with such weak-brained support-line "programmers" who is not even able to logically analyze such a simple and straightforward log file...

**Comment by garry0garry** [comment]
Hello!
Attached is the developer's full response.
https://github.com/JimStar/reolink_cctv/discussions/32#discussioncomment-3922049
Briefly: all data is transmitted to the cams in double quotes.

The error shows up randomly. The probability of having an error is much
lower if you first reboot the cam, then connect during the first minutes.

I have the following cams:
Reolink RLC-520A hw IPC_523128M5MP v3.1.0.951_22041566 - 9 pcs.
Reolink RLC-520A hw IPC_523128M5MP_V2 v3.1.0.1228_22082201 - 2 pcs.
Reolink RLC-511WA hw IPC_523128M5MP v3.1.0.956_22041509 - 1 pc.


чт, 20 окт. 2022 г. в 23:22, Jim Star ***@***.***>:

**Comment by garry0garry** [comment]
I replied to Reolink, but I replied to the integration developer :-( Sorry!
